### ISSUE TITLE
patches' license, and integration into official sdk

### ISSUE THREAD

**Issue by jdek** [soarqin/vitasdk-build#1]
We'd like to use your patches in the official vitasdk toolchain. To make it easier down the line, and potentially upstream the patches (or parts of them), could you release the patches into the public domain? (or point us to who can do this, if they're not yours)

**Comment by soarqin** [comment]
MinGW patches are from new BSD licensed mingw-builds project(https://github.com/niXman/mingw-builds), GCC/binutils common patches are just modified from vitasdk official patches to work with newest versions, so surely these patches can be used by official sdk. Binutils 2.27 new patches are built from some commits in its repository, as mentioned in vitasdk/vita-toolchain#52, so this part of patches should be under GPLv3 license
